### ISSUE TITLE
README Feedback

### ISSUE THREAD

**Issue by lisancao** [mariamarab/RNAgen#2]
Hey there! I notice your readme isn't on the repo, if I am at the wrong place and you have a readme somewhere else (e.g. a google doc, etc) let me know! :) 

Hackseq expectations of readme's include: 

- Project Blurb
- Project Background
- Features
- Installation Instructions (if possible)
- Note for prospective contributors
- List of Team Members

Once your readme is completed please let one of the Hackseq organizers know

**Comment by mariamarab** [comment]
Done, see `README.md` in the root dir
